version: "3.7"
services:
  xia:
    build: ./
    container_name: xia
    ports:
    - 8080:8080
    volumes:
    - "./volume/xia:/tmp"
    networks:
      base_net:
        ipv4_address: 11.11.11.3
networks:
  base_net:
    external:
      name: base