server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://212.64.19.109:3306/xia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: c2hhb2Zlbmd4aWE=

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chen.xia.entity