server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://212.64.19.109:3306/xia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: c2hhb2Zlbmd4aWE=
  redis:
    database: 0
    host: 212.64.19.109
    port: 6379
    password: qwer1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 300



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chen.xia.entity
